In [1]:
import numpy as np 
import seaborn as sns 
import pandas as pd 
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('../data/sifra-ai-dataset.csv')
df

,exercise,knee_angle,elbow_angle,hip_angle,body_angle,symmetry_score,landmark_visibility,form_label
0,plank,NaN,NaN,177.277440,173.443771,0.980495,0.883269,plank_correct
1,plank,NaN,NaN,148.181538,155.808066,0.982693,0.884278,plank_hips_high
2,pushup,NaN,83.034317,152.304493,145.856732,0.993650,0.869423,pushup_hips_high
3,pushup,NaN,82.615740,174.706470,178.097925,0.996957,0.883972,pushup_correct
4,pushup,NaN,68.553589,175.997185,179.385176,0.960992,0.958429,pushup_correct
...,...,...,...,...,...,...,...,...
907,squat,111.382295,NaN,100.588779,166.860051,0.963570,0.857370,shallow
908,squat,81.976948,NaN,92.060456,154.956824,0.801158,0.996518,knees_caving
909,plank,NaN,NaN,150.790653,154.737417,0.898746,0.842262,plank_hips_low
910,pushup,NaN,112.516983,178.046371,178.886172,0.951105,0.905064,pushup_elbow_flare
911,squat,99.390416,NaN,107.026766,170.696342,0.947417,0.951632,shallow

In [4]:
df.shape

(912, 8)

In [5]:
df.head(5)

,exercise,knee_angle,elbow_angle,hip_angle,body_angle,symmetry_score,landmark_visibility,form_label
0,plank,NaN,NaN,177.277440,173.443771,0.980495,0.883269,plank_correct
1,plank,NaN,NaN,148.181538,155.808066,0.982693,0.884278,plank_hips_high
2,pushup,NaN,83.034317,152.304493,145.856732,0.993650,0.869423,pushup_hips_high
3,pushup,NaN,82.615740,174.706470,178.097925,0.996957,0.883972,pushup_correct
4,pushup,NaN,68.553589,175.997185,179.385176,0.960992,0.958429,pushup_correct

In [6]:
df.describe()

,knee_angle,elbow_angle,hip_angle,body_angle,symmetry_score,landmark_visibility
count,305.000000,303.000000,912.000000,907.000000,904.000000,907.000000
mean,92.274076,89.691302,138.903615,163.082347,0.921950,0.911066
std,15.080442,14.853429,37.781709,12.526082,0.059638,0.040224
min,64.154332,59.489761,52.378109,112.694056,0.613320,0.774063
25%,80.889556,78.721652,100.646533,154.098664,0.899655,0.883381
50%,88.261990,86.540444,153.124354,163.959387,0.935944,0.912590
75%,100.231422,98.567615,171.537492,173.958416,0.961292,0.938652
max,138.276531,133.211434,180.000000,180.000000,1.000000,1.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   exercise             912 non-null    object
 1   knee_angle           305 non-null    float64
 2   elbow_angle          303 non-null    float64
 3   hip_angle            912 non-null    float64
 4   body_angle           907 non-null    float64
 5   symmetry_score       904 non-null    float64
 6   landmark_visibility  907 non-null    float64
 7   form_label           912 non-null    object
dtypes: float64(6), object(2)
memory usage: 57.1+ KB

In [8]:
df.isna().sum()

exercise                 0
knee_angle             607
elbow_angle            609
hip_angle                0
body_angle               5
symmetry_score           8
landmark_visibility      5
form_label               0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(12)

In [12]:
df.drop_duplicates()

,exercise,knee_angle,elbow_angle,hip_angle,body_angle,symmetry_score,landmark_visibility,form_label
0,plank,NaN,NaN,177.277440,173.443771,0.980495,0.883269,plank_correct
1,plank,NaN,NaN,148.181538,155.808066,0.982693,0.884278,plank_hips_high
2,pushup,NaN,83.034317,152.304493,145.856732,0.993650,0.869423,pushup_hips_high
3,pushup,NaN,82.615740,174.706470,178.097925,0.996957,0.883972,pushup_correct
4,pushup,NaN,68.553589,175.997185,179.385176,0.960992,0.958429,pushup_correct
...,...,...,...,...,...,...,...,...
907,squat,111.382295,NaN,100.588779,166.860051,0.963570,0.857370,shallow
908,squat,81.976948,NaN,92.060456,154.956824,0.801158,0.996518,knees_caving
909,plank,NaN,NaN,150.790653,154.737417,0.898746,0.842262,plank_hips_low
910,pushup,NaN,112.516983,178.046371,178.886172,0.951105,0.905064,pushup_elbow_flare
911,squat,99.390416,NaN,107.026766,170.696342,0.947417,0.951632,shallow

In [15]:
df.columns

Index(['exercise', 'knee_angle', 'elbow_angle', 'hip_angle', 'body_angle',
       'symmetry_score', 'landmark_visibility', 'form_label'],
      dtype='object')

In [22]:
df['knee_angle']=df['knee_angle'].fillna(df['knee_angle'].mean())
df['elbow_angle']=df['elbow_angle'].fillna(df['elbow_angle'].mean())
df['body_angle']=df['body_angle'].fillna(df['body_angle'].mean())
df['symmetry_score']=df['symmetry_score'].fillna(df['symmetry_score'].mean()) 
df['landmark_visibility']=df['landmark_visibility'].fillna(df['landmark_visibility'].mean()) 



df.isna().sum()

exercise               0
knee_angle             0
elbow_angle            0
hip_angle              0
body_angle             0
symmetry_score         0
landmark_visibility    0
form_label             0
elbow_angle_angle      0
dtype: int64

In [23]:
df.dtypes

exercise                object
knee_angle             float64
elbow_angle            float64
hip_angle              float64
body_angle             float64
symmetry_score         float64
landmark_visibility    float64
form_label              object
elbow_angle_angle      float64
dtype: object

In [24]:
# Numerical columns
numeric_cols = [
    "knee_angle",
    "elbow_angle",
    "hip_angle",
    "body_angle",
    "symmetry_score",
    "landmark_visibility"
]

# Convert numerical columns to numeric
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Categorical columns
df["exercise"] = df["exercise"].astype("string")
df["form_label"] = df["form_label"].astype("string")

# Check again
df.dtypes

exercise               string[python]
knee_angle                    float64
elbow_angle                   float64
hip_angle                     float64
body_angle                    float64
symmetry_score                float64
landmark_visibility           float64
form_label             string[python]
elbow_angle_angle             float64
dtype: object

In [25]:
# Check angle ranges
angle_cols = [
    "knee_angle",
    "elbow_angle",
    "hip_angle",
    "body_angle"
]

for col in angle_cols:
    print(f"\n{col}")
    print(df[(df[col] < 0) | (df[col] > 180)][[col]])

knee_angle
Empty DataFrame
Columns: [knee_angle]
Index: []

elbow_angle
Empty DataFrame
Columns: [elbow_angle]
Index: []

hip_angle
Empty DataFrame
Columns: [hip_angle]
Index: []

body_angle
Empty DataFrame
Columns: [body_angle]
Index: []

In [26]:
print("Exercise values:")
print(df["exercise"].unique())

print("\nForm labels:")
print(df["form_label"].unique())

Exercise values:
<StringArray>
['plank', 'pushup', 'squat']
Length: 3, dtype: string

Form labels:
<StringArray>
[     'plank_correct',    'plank_hips_high',   'pushup_hips_high',
     'pushup_correct',     'plank_hips_low',       'knees_caving',
            'correct',    'pushup_body_sag', 'pushup_elbow_flare',
       'forward_lean',            'shallow']
Length: 11, dtype: string

In [27]:
valid_labels = [
    "correct",
    "shallow",
    "forward_lean",
    "knees_caving",
    "pushup_correct",
    "pushup_elbow_flare",
    "pushup_body_sag",
    "pushup_hips_high",
    "plank_correct",
    "plank_hips_high",
    "plank_hips_low"
]

invalid_labels = df[~df["form_label"].isin(valid_labels)]

print("Invalid form-label rows:")
print(invalid_labels)

Invalid form-label rows:
Empty DataFrame
Columns: [exercise, knee_angle, elbow_angle, hip_angle, body_angle, symmetry_score, landmark_visibility, form_label, elbow_angle_angle]
Index: []

In [34]:
df.columns

Index(['exercise', 'knee_angle', 'elbow_angle', 'hip_angle', 'body_angle',
       'symmetry_score', 'landmark_visibility', 'form_label'],
      dtype='object')

In [35]:
df.drop(columns=["elbow_angle_angle"], inplace=True)

KeyError: "['elbow_angle_angle'] not found in axis"

In [37]:
df.to_csv("../data/cleaned.csv", index=False)